#
# Auto-generated packaging section.
# Generated by: spectacle version 0.32
#

Name:       harbour-spotambience

# >> macros
# << macros

Summary:    Spot-price ambience automation for Sailfish OS
Version:    1.0.0
Release:    1
Group:      Applications/Internet
License:    GPLv3
URL:        https://github.com/Ag9HOn/spot-ambience
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-spotambience.yaml
Requires:   sailfishsilica-qt5
BuildRequires:  pkgconfig(sailfishapp)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(mlite5)
BuildRequires:  cmake
BuildRequires:  desktop-file-utils

%description
Spot Ambience follows Finland's quarter-hour day-ahead electricity prices,
presents history and forecasts, and changes the active Sailfish ambience.
Spot price data: Nord Pool day-ahead prices for Finland, published through
Elering LIVE by Elering AS.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake .
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

desktop-file-install --delete-original \
  --dir %{buildroot}%{_datadir}/applications \
  %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}/qml
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/icons/hicolor/108x108/apps/%{name}.png
%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{_datadir}/icons/hicolor/172x172/apps/%{name}.png
# >> files
# << files
